# Generated by Django 3.1.1 on 2020-09-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_auto_20200920_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
