# Generated by Django 3.1.1 on 2020-09-28 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0009_auto_20200928_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brands',
            old_name='slug',
            new_name='brand_slug',
        ),
    ]
