# Generated by Django 3.1.1 on 2020-09-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200919_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlepage',
            options={'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='singlepage',
            name='show_page',
            field=models.BooleanField(default=True),
        ),
    ]
