# Generated by Django 3.1.1 on 2020-09-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20200922_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepage',
            name='page_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
