# Generated by Django 3.1.1 on 2020-09-22 13:23

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_singlepage_page_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepage',
            name='full_body',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
