# Generated by Django 3.1.1 on 2020-09-22 14:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20200922_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlepage',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
