# Generated by Django 3.1.1 on 2020-09-22 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_singlepage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlepage',
            name='content',
        ),
    ]
