# Generated by Django 3.1.1 on 2020-09-22 15:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_singlepage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlepage',
            name='content',
        ),
        migrations.AlterField(
            model_name='singlepage',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
