# Generated by Django 3.1.1 on 2020-09-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20200924_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='name',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='event_type',
            field=models.CharField(choices=[('seminar', 'سمینار'), ('exhibition', 'نمایشگاه')], default='seminar', max_length=15),
        ),
    ]
