# Generated by Django 3.1.1 on 2020-09-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20200924_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='event_type',
        ),
        migrations.AddField(
            model_name='eventtype',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True, unique_for_date='publish'),
        ),
    ]
