# Generated by Django 3.1.1 on 2020-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20200924_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('seminar', 'سمینار'), ('exhibition', 'نمایشگاه')], default='seminar', max_length=15),
        ),
    ]
