# Generated by Django 3.1.1 on 2020-09-26 13:34

from django.db import migrations, models
import django.utils.timezone
import event.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_event_event_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-publish',), 'verbose_name': 'رویداد', 'verbose_name_plural': 'رویدادها'},
        ),
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'نوع رویداد', 'verbose_name_plural': 'انواع رویداد'},
        ),
        migrations.AlterField(
            model_name='event',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='متن کامل'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='نوشته شده در'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_index',
            field=models.IntegerField(verbose_name='ترتیب نمایش'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('seminar', 'سمینار'), ('exhibition', 'نمایشگاه')], default='seminar', max_length=15, verbose_name='نوع رویداد'),
        ),
        migrations.AlterField(
            model_name='event',
            name='events',
            field=models.ForeignKey(on_delete=models.SET(event.models.get_deleted_event_type), to='event.eventtype', verbose_name='ارتباط با کدام رویداد'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر در'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=250, unique=True, unique_for_date='publish', verbose_name='آدرس لینک'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('published', 'منتشر شده')], default='draft', max_length=10, verbose_name='وضعیت نمایش'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان رویداد'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='نوع رویداد'),
        ),
    ]
