# Generated by Django 3.1.1 on 2020-09-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200920_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='show_menu',
            field=models.BooleanField(default=True),
        ),
    ]
